# Tells GitHub Pages to exclude the server folder and root node_modules from the Jekyll build process
exclude:
  - server/
  - node_modules/

# Ensure Jekyll doesn't try to build files *outside* the client/build folder
# This is a general safety measure, not strictly required by the error but good practice.
# It tells Jekyll to only consider the root as its source, which is then refined by `exclude`.
# For a project where we deploy from a subfolder, Jekyll's processing of the root can be tricky.
# The key here is the 'exclude'.
